export const INITIAL_IDEAS = [
    {
        id: '1',
        title: 'EcoTrack: Personal Carbon Footprint API',
        shortDesc: 'A unified API for developers to easily calculate real-time carbon offsets for e-commerce checkouts.',
        longDesc: 'EcoTrack solves the complex problem of measuring carbon footprints for individual online purchases. We provide a developer-friendly API that integrates into major e-commerce platforms (Shopify, WooCommerce, Magento). When a user checks out, we instantly calculate the shipping emission based on distance and weight, offering a one-click offset micro-transaction. Our goal is to make sustainability effortless for both the retailer and the consumer.',
        category: 'Tech',
        tags: ['API', 'Sustainability', 'E-commerce'],
        author: 'Sarah Chen',
        authorId: 'user-1',
        estimatedBudget: '$50k - $100k',
        targetAudience: 'E-commerce Developers, Sustainable Brands',
        problemStatement: 'Calculating per-transaction carbon footprint requires complex logistics APIs and emission conversion models that most small-medium businesses cannot afford to implement.',
        proposedSolution: 'A scalable REST API that abstracts the calculation and partners directly with verified carbon offset projects to automate the supply chain of sustainability.',
        imageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&q=80',
        createdAt: '2026-05-10T10:00:00Z',
        likes: 124,
        comments: [
            { id: 'c1', userId: 'user-2', userName: 'David Kim', text: 'Brilliant! Would pay a premium for this plugin on Shopify.', createdAt: '2026-05-11T14:20:00Z' },
            { id: 'c2', userId: 'user-3', userName: 'Emma Wright', text: 'How do you verify the offset projects? That is usually the bottleneck.', createdAt: '2026-05-12T09:15:00Z', isEdited: false }
        ]
    },
    {
        id: '2',
        title: 'NeuroFlow: AI Sleep Optimization Wearable',
        shortDesc: 'A comfortable, non-intrusive headband that uses safe audio frequencies to induce deep sleep states.',
        longDesc: 'NeuroFlow uses state-of-the-art EEG sensors packed inside a breathable sleeping band. By monitoring brainwaves in real-time, it plays customized binaural ambient sounds that guide the brain into deeper REM cycles. Unlike normal sleep trackers that just give you data, NeuroFlow actually intervenes to fix your sleep architecture safely and naturally.',
        category: 'Health',
        tags: ['Wearable', 'AI', 'Wellness'],
        author: 'Dr. Marcus Webb',
        authorId: 'user-4',
        estimatedBudget: '$200k+',
        targetAudience: 'Insomniacs, Biohackers, High Performers',
        problemStatement: 'Current wearables only track sleep but do not actively improve it in real-time.',
        proposedSolution: 'Closed-loop audio stimulation based on real-time brainwave monitoring to optimize sleep stages instantaneously.',
        imageUrl: 'https://images.unsplash.com/photo-1512438248247-f0f2a5a8b7f0?w=800&q=80',
        createdAt: '2026-05-12T08:30:00Z',
        likes: 342,
        comments: []
    },
    {
        id: '3',
        title: 'LearnSphere: VR Classrooms for Remote Kids',
        shortDesc: 'Immersive educational environments that bring the physical classroom experience to remote learning.',
        longDesc: 'LearnSphere is building a platform for Quest and Vision Pro that allows teachers to host completely interactive, physics-based virtual classrooms. Kids can perform chemistry experiments safely, visit historical sites in 3D, and interact with peers via spatial audio, solving the isolation problem of standard remote video calls.',
        category: 'Education',
        tags: ['VR/AR', 'EdTech', 'Metaverse'],
        author: 'Elena Rodriguez',
        authorId: 'user-5',
        estimatedBudget: '$150k - $300k',
        targetAudience: 'Remote Schools, Homeschooling Parents, Tutors',
        problemStatement: 'Zoom classes lead to high unengagement rates and lack the spatial, hands-on learning crucial for child development.',
        proposedSolution: 'A localized multiplayer VR engine specialized in educational physics and safe social interaction.',
        imageUrl: 'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&q=80',
        createdAt: '2026-05-14T11:45:00Z',
        likes: 89,
        comments: []
    },
    {
        id: '4',
        title: 'FinAlign: Micro-Investing for Freelancers',
        shortDesc: 'Automated fractional investing that scales with unpredictable income streams.',
        longDesc: 'Freelancers have variable income which makes traditional monthly saving plans fail. FinAlign connects to freelancer bank accounts, detects incoming payments, and algorithms determine a safe percentage to sweep into a diversified ETF portfolio without hurting short-term liquidity needs.',
        category: 'Fintech',
        tags: ['Investing', 'Freelance', 'Automation'],
        author: 'James H',
        authorId: 'user-6',
        estimatedBudget: '$100k - $200k',
        targetAudience: 'Freelancers, Gig Economy Workers',
        problemStatement: 'Variable income makes strict monthly budgeting and investing impossible for gig workers.',
        proposedSolution: 'Dynamic percentage-based sweep accounts powered by predictive cash flow AI.',
        imageUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&q=80',
        createdAt: '2026-05-15T16:20:00Z',
        likes: 210,
        comments: []
    },
    {
        id: '5',
        title: 'CodeReview.ai: Instant PR Feedback',
        shortDesc: 'AI-agents that instantly review pull requests for logic flaws, security, and styling.',
        longDesc: 'Hooking directly into GitHub and GitLab, CodeReview.ai runs local LLM instances that understand your entire repository context. It leaves human-like comments on PRs within seconds of creation, drastically reducing the bottleneck for senior engineers while maintaining code quality.',
        category: 'AI',
        tags: ['DevTools', 'LLM', 'Productivity'],
        author: 'Alex Doe',
        authorId: 'mock-user-1', // Matches mock user
        estimatedBudget: '$50k',
        targetAudience: 'Software Teams, Open Source Maintainers',
        problemStatement: 'Human PR reviews take too much time and block rapid deployment cycles.',
        proposedSolution: 'Context-aware AI reviews that handle 80% of routine checks.',
        imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
        createdAt: '2026-05-16T09:10:00Z',
        likes: 531,
        comments: [
            { id: 'c3', userId: 'user-3', userName: 'Emma Wright', text: 'I use something similar, but context length is always an issue. How do you feed the whole repo?', createdAt: '2026-05-16T12:00:00Z' }
        ]
    },
    {
        id: '6',
        title: 'MediChain: Secure Patient Data Transfer',
        shortDesc: 'Blockchain protocol for instant, secure sharing of medical records between hospitals.',
        longDesc: 'Instead of faxing records or relying on fragmented portals, MediChain uses zero-knowledge proofs on a private ledger. Patients hold the keys to their data and can instantly grant read-access to any specialist worldwide, ensuring 100% HIPAA compliance and removing administrative friction.',
        category: 'Health',
        tags: ['Blockchain', 'Security', 'Healthcare'],
        author: 'Dr. Anna Lee',
        authorId: 'user-7',
        estimatedBudget: '$500k+',
        targetAudience: 'Hospitals, Clinics, Patients with complex conditions',
        problemStatement: 'Medical records are siloed, leading to redundant tests and dangerous lack of context during emergencies.',
        proposedSolution: 'A zero-knowledge blockchain architecture giving patients control over unified medical histories.',
        imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80',
        createdAt: '2026-05-17T14:00:00Z',
        likes: 195,
        comments: []
    },
    {
        id: '7',
        title: 'AgriSense: IoT Soil Health Predictor',
        shortDesc: 'Low-cost, solar-powered soil sensors paired with satellite telemetry for smallholder farmers.',
        longDesc: 'AgriSense democratizes precision agriculture. We provide affordable, biodegradable soil spikes that measure nitrogen, phosphorus, potassium, and moisture content in real-time. This localized telemetry is paired with localized weather micro-models to deliver predictive irrigation and fertilizer alerts via simple SMS or WhatsApp messages, helping farmers increase crop yields while cutting resource waste by 30%.',
        category: 'Tech',
        tags: ['IoT', 'Agriculture', 'Sustainability'],
        author: 'Rajesh Patel',
        authorId: 'user-8',
        estimatedBudget: '$75k - $120k',
        targetAudience: 'Independent Farmers, Agricultural Cooperatives',
        problemStatement: 'Commercial precision farming hardware is priced out of reach for small-scale operations, causing reliance on dangerous overuse of fertilizers.',
        proposedSolution: 'A mesh-networked IoT sensor suite with a zero-data-plan communication fallback layered beneath a lightweight predictive analysis engine.',
        imageUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad451?w=800&q=80',
        createdAt: '2026-05-18T07:30:00Z',
        likes: 156,
        comments: [
            { id: 'c4', userId: 'user-2', userName: 'David Kim', text: 'How do the sensors hold up in heavy clay soils or extreme freeze/thaw cycles?', createdAt: '2026-05-18T11:15:00Z' }
        ]
    },
    {
        id: '8',
        title: 'LegalEase: AI Contract Breakdown for SMBs',
        shortDesc: 'An intelligent legal copilot that parses complex corporate contracts into plain, jargon-free English.',
        longDesc: 'Small business owners frequently sign vendors, leases, and NDAs without fully understanding the hidden liability traps. LegalEase instantly highlights unfavorable clauses, indemnification traps, and auto-renewal fine print. It compares the document against industry standard benchmarks and gives you a localized negotiation playbook before you spend thousands on standard legal retainers.',
        category: 'AI',
        tags: ['LegalTech', 'LLM', 'Business'],
        author: 'Simone Vance, Esq.',
        authorId: 'user-9',
        estimatedBudget: '$60k',
        targetAudience: 'Small Business Owners, Agencies, Freelancers',
        problemStatement: 'Legal fees are a structural barrier for small teams, forcing them to assume unknown operational liabilities.',
        proposedSolution: 'A localized Retrieval-Augmented Generation (RAG) system trained strictly on verified corporate case law to spot hostile clauses.',
        imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80',
        createdAt: '2026-05-18T15:40:00Z',
        likes: 289,
        comments: []
    },
    {
        id: '9',
        title: 'NutriKit: Smart Allergen Food Tracker',
        shortDesc: 'A micro-spectrometer phone accessory that scans meals for trace food allergens in seconds.',
        longDesc: 'NutriKit is a consumer hardware solution for people dealing with severe food allergies. It consists of a tiny, clip-on optical scanner that reads the molecular signature of restaurant foods or supermarket items. By shooting light pulses through a bite of food, it returns a precise protein analysis to your phone, alerting you to trace amounts of gluten, peanuts, shellfish, or dairy.',
        category: 'Health',
        tags: ['Hardware', 'Wellness', 'Biotech'],
        author: 'Chloe Dupont',
        authorId: 'user-10',
        estimatedBudget: '$250k - $400k',
        targetAudience: 'Severe Allergy Suffers, Parents of Celiac Kids',
        problemStatement: 'Cross-contamination in restaurant kitchens leads to unexpected, life-threatening allergic reactions despite verbal confirmation.',
        proposedSolution: 'Near-Infrared (NIR) spectroscopy mapped against a constantly expanding crowd-sourced database of chemical food signatures.',
        imageUrl: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&q=80',
        createdAt: '2026-05-19T09:12:00Z',
        likes: 412,
        comments: [
            { id: 'c5', userId: 'user-5', userName: 'Elena Rodriguez', text: 'As a mother of a child with severe peanut anaphylaxis, I need this to hit production yesterday.', createdAt: '2026-05-19T14:22:00Z' }
        ]
    },
    {
        id: '10',
        title: 'SoundScape: Spatial Soundproofing Panels',
        shortDesc: 'Metamaterial modular acoustic panels that actively cancel street frequencies inside urban apartments.',
        longDesc: 'Traditional soundproofing is thick, destructive to drywall, and fails at stopping heavy, low-frequency rumbles like buses or subways. SoundScape creates lightweight, peel-and-stick wall panels designed with micro-engineered internal mazes (acoustic metamaterials). They catch specific street noise frequencies and trap them, bouncing the sound waves against themselves until they completely dissipate.',
        category: 'Hardware',
        tags: ['Design', 'Urban Living', 'PropTech'],
        author: 'Liam Vance',
        authorId: 'user-11',
        estimatedBudget: '$180k',
        targetAudience: 'City Dwellers, WFH Professionals, Renters',
        problemStatement: 'Low-frequency urban noise pollution degrades sleep quality and focus, yet renters cannot legally modify structural walls.',
        proposedSolution: 'Sub-wavelength geometric resonators embedded into aesthetically pleasing, non-destructive modular wall finishes.',
        imageUrl: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80',
        createdAt: '2026-05-19T18:05:00Z',
        likes: 177,
        comments: []
    },
    {
        id: '11',
        title: 'DeFiWills: Self-Executing Digital Inheritances',
        shortDesc: 'A non-custodial smart contract system that securely transfers crypto and data assets upon death.',
        longDesc: 'Millions of dollars in digital wealth are permanently lost when people unexpectedly pass away because their family cannot locate seed phrases or passwords. DeFiWills acts as a decentralized dead-man\'s switch. By monitoring your wallet activity or cross-checking official public death registries, it automatically triggers a secure cryptographic decryption and payout protocol to pre-designated beneficiary public keys.',
        category: 'Fintech',
        tags: ['Blockchain', 'Security', 'Web3'],
        author: 'Marcus Vance',
        authorId: 'user-12',
        estimatedBudget: '$120k - $200k',
        targetAudience: 'Crypto Investors, Estate Planners, High Net Worth Individuals',
        problemStatement: 'Traditional legal wills cannot safely handle or execute the recovery of decentralized cryptographic private keys without exposing security vulnerabilities.',
        proposedSolution: 'Time-locked multi-signature smart contracts tied to verifiable real-world oracle endpoints.',
        imageUrl: 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?w=800&q=80',
        createdAt: '2026-05-20T10:45:00Z',
        likes: 233,
        comments: []
    },
    {
        id: '12',
        title: 'SkillSwap: Decentralized Corporate Training',
        shortDesc: 'An internal peer-to-peer micro-mentorship web platform that replaces generic video training libraries.',
        longDesc: 'Instead of forcing employees to click through boring, pre-recorded enterprise training courses, SkillSwap facilitates micro-learning loops right inside your company. An engineer who needs to learn AWS architecture can instantly swap an hour of their time with a cloud architect who wants to learn advanced React state handling. The system builds a dynamic graph of internal talent, saving money on external coaches.',
        category: 'Education',
        tags: ['Productivity', 'HRTech', 'SaaS'],
        author: 'Tariq Al-Mansoor',
        authorId: 'user-13',
        estimatedBudget: '$45k',
        targetAudience: 'Enterprise HR Departments, Fast-growing Tech Orgs',
        problemStatement: 'Corporate upskilling libraries suffer from low engagement rates because the generic video tutorials miss internal stack architecture context.',
        proposedSolution: 'An automated token-incentivized matching queue integrated with Slack and Microsoft Teams to streamline cross-department knowledge sharing.',
        imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80',
        createdAt: '2026-05-21T13:10:00Z',
        likes: 94,
        comments: [
            { id: 'c6', userId: 'mock-user-1', userName: 'Alex Doe', text: 'This would completely fix our engineering onboarding bottleneck.', createdAt: '2026-05-21T15:02:00Z' }
        ]
    }
];
